INSERT INTO exercises (id, name, slug, description, technique, difficulty, equipment,
                       primary_muscle_group, secondary_muscle_groups, video_url,
                       thumbnail_url, is_active, created_at, updated_at)
VALUES
-- Грудь
('a1b2c3d4-e5f6-7890-abcd-ef1234567890',
 'Жим штанги лёжа',
 'bench-press',
 'Базовое упражнение для развития грудных мышц',
 'Лягте на скамью, возьмитесь за штангу хватом чуть шире плеч. Опустите штангу к нижней части груди, затем выжмите вверх.',
 'BEGINNER',
 'BARBELL',
 'CHEST',
 ARRAY['TRICEPS', 'SHOULDERS'],
 'https://example.com/videos/bench-press.mp4',
 'https://example.com/images/bench-press.jpg',
 TRUE,
 NOW(), NOW()),

('b2c3d4e5-f6a7-8901-bcde-f12345678901',
 'Жим гантелей лёжа',
 'dumbbell-bench-press',
 'Альтернатива жиму штанги с большей амплитудой',
 'Лягте на скамью с гантелями в руках. Опустите гантели к груди, затем выжмите вверх.',
 'BEGINNER',
 'DUMBBELL',
 'CHEST',
 ARRAY['TRICEPS', 'SHOULDERS'],
 'https://example.com/videos/dumbbell-bench.mp4',
 'https://example.com/images/dumbbell-bench.jpg',
 TRUE,
 NOW(), NOW()),

-- Спина
('c3d4e5f6-a7b8-9012-cdef-123456789012',
 'Подтягивания',
 'pull-ups',
 'Базовое упражнение для развития широчайших мышц спины',
 'Возьмитесь за перекладину хватом сверху. Подтянитесь, пока подбородок не окажется над перекладиной.',
 'INTERMEDIATE',
 'PULL_UP_BAR',
 'BACK',
 ARRAY['BICEPS', 'FOREARMS'],
 'https://example.com/videos/pull-ups.mp4',
 'https://example.com/images/pull-ups.jpg',
 TRUE,
 NOW(), NOW()),

('d4e5f6a7-b8c9-0123-defa-234567890123',
 'Тяга штанги в наклоне',
 'barbell-row',
 'Базовое упражнение для толщины спины',
 'Наклонитесь вперёд, возьмите штангу. Тяните штангу к нижней части живота, сводя лопатки.',
 'INTERMEDIATE',
 'BARBELL',
 'BACK',
 ARRAY['BICEPS', 'FOREARMS'],
 'https://example.com/videos/barbell-row.mp4',
 'https://example.com/images/barbell-row.jpg',
 TRUE,
 NOW(), NOW()),

-- Ноги
('e5f6a7b8-c9d0-1234-efab-345678901234',
 'Приседания со штангой',
 'barbell-squat',
 'Король упражнений для развития ног',
 'Положите штангу на верхнюю часть спины. Приседайте, пока бёдра не станут параллельны полу.',
 'INTERMEDIATE',
 'BARBELL',
 'LEGS',
 ARRAY['GLUTES', 'CORE'],
 'https://example.com/videos/squat.mp4',
 'https://example.com/images/squat.jpg',
 TRUE,
 NOW(), NOW()),

('f6a7b8c9-d0e1-2345-fabc-456789012345',
 'Становая тяга',
 'deadlift',
 'Базовое упражнение для всего тела',
 'Встаньте перед штангой, возьмитесь за гриф. Поднимите штангу, выпрямляя ноги и спину одновременно.',
 'ADVANCED',
 'BARBELL',
 'LEGS',
 ARRAY['BACK', 'CORE', 'FOREARMS'],
 'https://example.com/videos/deadlift.mp4',
 'https://example.com/images/deadlift.jpg',
 TRUE,
 NOW(), NOW()),

-- Плечи
('a7b8c9d0-e1f2-3456-abcd-567890123456',
 'Жим штанги стоя',
 'overhead-press',
 'Базовое упражнение для развития плеч',
 'Возьмите штангу на грудь. Выжмите штангу вверх над головой, полностью выпрямляя руки.',
 'INTERMEDIATE',
 'BARBELL',
 'SHOULDERS',
 ARRAY['TRICEPS', 'CORE'],
 'https://example.com/videos/overhead-press.mp4',
 'https://example.com/images/overhead-press.jpg',
 TRUE,
 NOW(), NOW()),

-- Руки
('b8c9d0e1-f2a3-4567-bcde-678901234567',
 'Подъём штанги на бицепс',
 'barbell-curl',
 'Изолирующее упражнение для бицепса',
 'Встаньте прямо со штангой в руках. Сгибайте руки в локтях, поднимая штангу к плечам.',
 'BEGINNER',
 'BARBELL',
 'BICEPS',
 ARRAY['FOREARMS'],
 'https://example.com/videos/barbell-curl.mp4',
 'https://example.com/images/barbell-curl.jpg',
 TRUE,
 NOW(), NOW()),

('c9d0e1f2-a3b4-5678-cdef-789012345678',
 'Французский жим лёжа',
 'lying-triceps-extension',
 'Изолирующее упражнение для трицепса',
 'Лягте на скамью со штангой. Сгибайте руки в локтях, опуская штангу ко лбу, затем выпрямите руки.',
 'BEGINNER',
 'BARBELL',
 'TRICEPS',
 ARRAY[]::text[],
 'https://example.com/videos/lying-triceps.mp4',
 'https://example.com/images/lying-triceps.jpg',
 TRUE,
 NOW(), NOW()),

-- Пресс
('d0e1f2a3-b4c5-6789-defa-890123456789',
 'Скручивания',
 'crunches',
 'Базовое упражнение для пресса',
 'Лягте на спину, согните ноги в коленях. Поднимайте верхнюю часть тела, напрягая пресс.',
 'BEGINNER',
 'BODYWEIGHT',
 'CORE',
 ARRAY[]::text[],
 'https://example.com/videos/crunches.mp4',
 'https://example.com/images/crunches.jpg',
 TRUE,
 NOW(), NOW());