spring:
  application:
    name: recommendation-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/recommendation_db}
    username: ${DB_USERNAME:fit}
    password: ${DB_PASSWORD:fit_password}
    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false
    flyway:
      enabled: true
  server:
    port: 8085