services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: fit
      POSTGRES_PASSWORD: fit_password
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fit -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  auth-db-data: